version: "3"

services:
  node:
    build:
      context: .
      target: DEV
    depends_on:
      - mysql
    container_name: node
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    networks:
      - rede

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: petshop
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    networks:
      - rede

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - rede

networks:
  rede:
    driver: bridge
